//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsurancePortal.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Threading.Tasks;

    public partial class InsurancePortalEntities : DbContext, IUnitOfWork
    {
        public InsurancePortalEntities()
            : base("name=InsurancePortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<TemplateTab> TemplateTabs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<TemplateQue> TemplateQues { get; set; }

        public async Task<bool> SaveEntitiesAsync()
        {
            await base.SaveChangesAsync();
            return true;
        }

    }
}
